### ISSUE TITLE
Validate GCM and APN messages.

### ISSUE THREAD

**Issue by chrisdew** [chrisdew/jsonspace#38]
Invalid hex strings cause a crash.

```
{"apn_obj_tx":{"alert":"Message from [Dev] Lukes","token":"undefined","payload":{"published":{"channel":"se6APsM9jL","username":"4GvHffEMjE","data":"--redacted--"},"id":"2016-03-23T18:53:26.444Z|0|45.79.6.86|19885"}},"id":"2016-03-23T18:53:26.446Z|1|45.79.6.86|19885"}
SEND
buffer.js:594
        return this.hexWrite(string, offset, length);
                    ^

TypeError: Invalid hex string
    at TypeError (native)
    at Buffer.write (buffer.js:594:21)
    at fromString (buffer.js:113:26)
    at new Buffer (buffer.js:58:12)
    at new Device (/srv/node_modules/jsonspace/node_modules/apn/lib/device.js:13:16)
    at Array.send (/srv/node_modules/jsonspace/lib/protocol/apn.js:11:20)
    at Blackboard.put (/srv/node_modules/jsonspace/lib/blackboard.js:100:40)
    at /srv/node_modules/jsonspace/lib/blackboard.js:102:20
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)

npm ERR! Linux 4.4.0-x86_64-linode63
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! pubsub_jsonspace@0.16.2 start: `node pubsub.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pubsub_jsonspace@0.16.2 start script 'node pubsub.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pubsub_jsonspace package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pubsub.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pubsub_jsonspace
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/node_modules/pubsub/npm-debug.log
-e

**STOPPED** 2016-03-23

```

**Comment by fender** [comment]
@chrisdew Oops, thanks for flagging that. We should have realized we were sending `undefined`. We'll make sure we don't do that!

**Comment by fender** [comment]
@chrisdew Just in case you ever run into this yourself, it looks like iOS Simulators do not receive device tokens which is why it was passing `undefined` for that field.
